spring:
  application:
    name: hvlv-spring-cloud-api-gateway-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/hvlv?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver

  cloud:
    gateway:
      routes:
        - id: stock-enquiry
          uri: http://localhost:8700/
          predicates:
            - Path=/product-enquiry/**
        - id: user
          uri: http://localhost:8700/
          predicates:
            - Path=/user/**


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hvlv.microservices.springcloudapigatewayservice.hvlvspringcloudapigatewayservice.entity

eureka:
  client:
    service-url:
      defaultZone: http://topadmin:topadmin912@localhost:8761/eureka/

server:
  port: ${port:8900}

redis:
  database: 0
  # 集群设置 begin
  cluster:
    nodes:
      - 127.0.0.1:6379
    max-redirects: 5 # 获取失败 最大重定向次数
  #集群设置 end
  lettuce:
    pool:
      max-wait: 100000
      max-idle: 10
      max-active: 100
  timeout: 5000



