spring:
  application:
    name: hvlv-shipment-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/hvlv_db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
#spring:
#  application:
#    name: hvlv-shipment-service
#  datasource:
#    username: toplogistics
#    password: HL$9}CPwX~rC
#    url: jdbc:mariadb://database-1.cp7y5aejxebr.ap-southeast-2.rds.amazonaws.com:3306/hvlv_db?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hvlv.microservices.shipmentService.hvlvShipmentService.entity

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

eureka:
  client:
    service-url:
      defaultZone: http://topadmin:topadmin912@localhost:8761/eureka/

server:
  port: ${port:8811}
  # 8811

redis:
  database: 0
  # 集群设置 begin
  cluster:
    nodes:
      - 127.0.0.1:6379
    max-redirects: 10 # 获取失败 最大重定向次数
  #集群设置 end
  lettuce:
    pool:
      max-wait: 100000
      max-idle: 10
      max-active: 100
  timeout: 5000
